import Head from 'next/head'
import Typewriter from '@/components/Typewriter';
import Image from 'next/image';
import frat from '../public/fratphoto.jpg'

// import Brotherhood from '../components/Brotherhood'

export default function Home() {
  const words = ["brotherhood", "philanthropy organization", "professional community", "society of engineers", "family"];
  return (
    <div>
      <Head>
        <title>Theta Tau Theta Gamma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.png" />
      </Head>

      <div className="relative">
        <Image
          src={frat}
          alt="Full Fraternity Photo"
          className="w-full h-auto z-1"
        />

        <div className="absolute inset-0 tint-red z-2"></div>
        
        <div className="absolute inset-0 flex flex-col justify-center items-center text-white">
          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-8xl font-bold z-3 mt-2" >THETA TAU</h1>
          <h1 className="text-2xl sm:text-2xl md:text-4xl lg:text-6xl font-bold z-3" >THETA GAMMA</h1>
          <h2 className="text-lg sm:text-lg md:text-2xl lg:text-3xl font-semibold z-3 mt-2 text-center" >
            More than a fraternity, we are a{' '}
            <Typewriter words={words} />
          </h2>
        </div>
      </div>

      <div className="text-lg sm:text-base md:text-lg lg:text-xl px-4 pr-6 pl-6 text-center py-4 font-semibold z-3 mt-2">
        <p>
          Theta Tau is Professional Engineering Fraternity. As a group, we are dedicated to the professional and social development of our members into professionals that will enter the industry as strong, contributing members.
          Our chapter is known as Theta Gamma Chapter and is one of the largest chapters in the Country.
        </p>
      </div>

      <div className="text-lg sm:text-base md:text-lg lg:text-xl px-4 text-center pb-4 pr-6 pl-6  font-semibold z-3 mt-2">
      <p>Theta Tau is made up of smart, driven engineers who come
                        from a diverse range of backgrounds and majors. Our
                        chapter holds events weekly designed to instill a
                        brotherhood among our members and develop ourselves as
                        well as our college and University.</p>
      </div>
    
    
    </div>

  );
}
